//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jpp.Ironstone.Housing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jpp.Ironstone.Housing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Calculated line length between blocks: {0}.
        /// </summary>
        internal static string Command_Output_GradientLineLength {
            get {
                return ResourceManager.GetString("Command_Output_GradientLineLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Enter a gradient (1 in).
        /// </summary>
        internal static string Command_Prompt_EnterGradient {
            get {
                return ResourceManager.GetString("Command_Prompt_EnterGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Enter a invert (mm).
        /// </summary>
        internal static string Command_Prompt_EnterInvert {
            get {
                return ResourceManager.GetString("Command_Prompt_EnterInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Enter a level.
        /// </summary>
        internal static string Command_Prompt_EnterLevel {
            get {
                return ResourceManager.GetString("Command_Prompt_EnterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Include gradient.
        /// </summary>
        internal static string Command_Prompt_IncludeGradientBlock {
            get {
                return ResourceManager.GetString("Command_Prompt_IncludeGradientBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 3d polylines allowed..
        /// </summary>
        internal static string Command_Prompt_Reject3dPolyline {
            get {
                return ResourceManager.GetString("Command_Prompt_Reject3dPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only block references allowed..
        /// </summary>
        internal static string Command_Prompt_RejectBlockReference {
            get {
                return ResourceManager.GetString("Command_Prompt_RejectBlockReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select end level block.
        /// </summary>
        internal static string Command_Prompt_SelectEndLevelBlock {
            get {
                return ResourceManager.GetString("Command_Prompt_SelectEndLevelBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select end point.
        /// </summary>
        internal static string Command_Prompt_SelectEndPoint {
            get {
                return ResourceManager.GetString("Command_Prompt_SelectEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select back of footway point.
        /// </summary>
        internal static string Command_Prompt_SelectFootwayPoint {
            get {
                return ResourceManager.GetString("Command_Prompt_SelectFootwayPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select intermedia point between the two blocks.
        /// </summary>
        internal static string Command_Prompt_SelectMidPoint {
            get {
                return ResourceManager.GetString("Command_Prompt_SelectMidPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select road string.
        /// </summary>
        internal static string Command_Prompt_SelectRoadString {
            get {
                return ResourceManager.GetString("Command_Prompt_SelectRoadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select start level block.
        /// </summary>
        internal static string Command_Prompt_SelectStartLevelBlock {
            get {
                return ResourceManager.GetString("Command_Prompt_SelectStartLevelBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Select start point.
        /// </summary>
        internal static string Command_Prompt_SelectStartPoint {
            get {
                return ResourceManager.GetString("Command_Prompt_SelectStartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gradient block..
        /// </summary>
        internal static string Exception_NoGradientBlock {
            get {
                return ResourceManager.GetString("Exception_NoGradientBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No level block..
        /// </summary>
        internal static string Exception_NoLevelBlock {
            get {
                return ResourceManager.GetString("Exception_NoLevelBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Between Blocks.
        /// </summary>
        internal static string ExtensionApplication_UI_BtnBlockBetweenBlocks {
            get {
                return ResourceManager.GetString("ExtensionApplication_UI_BtnBlockBetweenBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Block.
        /// </summary>
        internal static string ExtensionApplication_UI_BtnGradientBetweenBlocks {
            get {
                return ResourceManager.GetString("ExtensionApplication_UI_BtnGradientBetweenBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Block At Gradient.
        /// </summary>
        internal static string ExtensionApplication_UI_BtnLevelBlockFromBlockAtGradient {
            get {
                return ResourceManager.GetString("ExtensionApplication_UI_BtnLevelBlockFromBlockAtGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Block With Invert.
        /// </summary>
        internal static string ExtensionApplication_UI_BtnLevelBlockFromBlockWithInvert {
            get {
                return ResourceManager.GetString("ExtensionApplication_UI_BtnLevelBlockFromBlockWithInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Point At Gradient.
        /// </summary>
        internal static string ExtensionApplication_UI_BtnLevelBlockFromPointAtGradient {
            get {
                return ResourceManager.GetString("ExtensionApplication_UI_BtnLevelBlockFromPointAtGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Block.
        /// </summary>
        internal static string ExtensionApplication_UI_BtnLevelBlocks {
            get {
                return ResourceManager.GetString("ExtensionApplication_UI_BtnLevelBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing.
        /// </summary>
        internal static string ExtensionApplication_UI_PanelTitle {
            get {
                return ResourceManager.GetString("ExtensionApplication_UI_PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gradient_large {
            get {
                object obj = ResourceManager.GetObject("gradient_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap level_block_large {
            get {
                object obj = ResourceManager.GetObject("level_block_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap level_block_small {
            get {
                object obj = ResourceManager.GetObject("level_block_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Invalid level block selected..
        /// </summary>
        internal static string Message_Invalid_Level_Block_Selected {
            get {
                return ResourceManager.GetString("Message_Invalid_Level_Block_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Levels set on blocks are equal..
        /// </summary>
        internal static string Message_Levels_Are_Equal {
            get {
                return ResourceManager.GetString("Message_Levels_Are_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///No level set on block..
        /// </summary>
        internal static string Message_No_Level_Set_On_Block {
            get {
                return ResourceManager.GetString("Message_No_Level_Set_On_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///No road string selected..
        /// </summary>
        internal static string Message_No_Road_String_Selected {
            get {
                return ResourceManager.GetString("Message_No_Road_String_Selected", resourceCulture);
            }
        }
    }
}
